"""Ajout du champ images dans Vehicule

Revision ID: 009edd7ac7e4
Revises: 97490b591719
Create Date: 2025-06-20 13:02:15.356153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009edd7ac7e4'
down_revision: Union[str, None] = '97490b591719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicules', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicules', 'images')
    # ### end Alembic commands ###
