"""Ajout desactiver garages

Revision ID: 19e5653d5570
Revises: 5a77d82a0047
Create Date: 2025-06-14 13:07:43.875268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e5653d5570'
down_revision: Union[str, None] = '5a77d82a0047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'is_active')
    # ### end Alembic commands ###
