"""Ajout description garage

Revision ID: 1b506df52c44
Revises: 19e5653d5570
Create Date: 2025-06-14 13:31:15.570065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b506df52c44'
down_revision: Union[str, None] = '19e5653d5570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'description')
    # ### end Alembic commands ###
