"""Add lat and lon columns to users

Revision ID: 1b8b34cb7577
Revises: b837a28f6692
Create Date: 2025-07-06 11:31:19.707829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8b34cb7577'
down_revision: Union[str, None] = 'b837a28f6692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lon')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###
