"""add date_creation to Garage

Revision ID: 1dd14282e079
Revises: 801ecc441256
Create Date: 2025-07-02 10:39:44.432908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd14282e079'
down_revision: Union[str, None] = '801ecc441256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('date_creation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'date_creation')
    # ### end Alembic commands ###
