"""Ajout type Vehicule

Revision ID: 2a88e935190d
Revises: 6842086a332f
Create Date: 2025-06-16 13:38:56.717098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a88e935190d'
down_revision: Union[str, None] = '6842086a332f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicules', 'type_vehicule',
               existing_type=mysql.ENUM('berline', 'suv', 'citadine', 'sport', 'cabriolet', 'break_'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicules', 'type_vehicule',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('berline', 'suv', 'citadine', 'sport', 'cabriolet', 'break_'),
               existing_nullable=False)
    # ### end Alembic commands ###
