"""Ajout is_active a User

Revision ID: 5a77d82a0047
Revises: 6466bc55e1fe
Create Date: 2025-06-12 17:34:36.270946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a77d82a0047'
down_revision: Union[str, None] = '6466bc55e1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reservations', 'users', ['utilisateur_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    # ### end Alembic commands ###
