"""Initial migration

Revision ID: 6466bc55e1fe
Revises: 
Create Date: 2025-06-11 16:22:52.428154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6466bc55e1fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avis',
    sa.Column('avis_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('garage_id', sa.Integer(), nullable=True),
    sa.Column('vehicule_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_avis', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.garage_id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.vehicule_id'], ),
    sa.PrimaryKeyConstraint('avis_id')
    )
    op.create_index(op.f('ix_avis_avis_id'), 'avis', ['avis_id'], unique=False)
    op.create_index(op.f('ix_vehicules_carburant'), 'vehicules', ['carburant'], unique=False)
    op.create_index(op.f('ix_vehicules_prix_par_jour'), 'vehicules', ['prix_par_jour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicules_prix_par_jour'), table_name='vehicules')
    op.drop_index(op.f('ix_vehicules_carburant'), table_name='vehicules')
    op.drop_index(op.f('ix_avis_avis_id'), table_name='avis')
    op.drop_table('avis')
    # ### end Alembic commands ###
