"""Ajout type Vehicule

Revision ID: 6842086a332f
Revises: 1b506df52c44
Create Date: 2025-06-16 12:41:17.574125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6842086a332f'
down_revision: Union[str, None] = '1b506df52c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicules', sa.Column('type_vehicule', sa.Enum('berline', 'suv', 'citadine', 'sport', 'cabriolet', 'break_', name='typevehiculeenum'), nullable=False))
    op.create_index(op.f('ix_vehicules_type_vehicule'), 'vehicules', ['type_vehicule'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicules_type_vehicule'), table_name='vehicules')
    op.drop_column('vehicules', 'type_vehicule')
    # ### end Alembic commands ###
