"""Ajout telephone pour garage

Revision ID: 801ecc441256
Revises: 009edd7ac7e4
Create Date: 2025-06-30 12:38:13.166525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801ecc441256'
down_revision: Union[str, None] = '009edd7ac7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('telephone', sa.String(20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'telephone')
    # ### end Alembic commands ###
