"""Ajout lat lon dans garage

Revision ID: b837a28f6692
Revises: dd803e9573e1
Create Date: 2025-07-06 10:25:30.298288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b837a28f6692'
down_revision: Union[str, None] = 'dd803e9573e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garages', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('garages', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garages', 'lon')
    op.drop_column('garages', 'lat')
    # ### end Alembic commands ###
