"""Ajout champs vehicule : boite_vitesse, nb_portes, etc.

Revision ID: dd803e9573e1
Revises: 1dd14282e079
Create Date: 2025-07-03 10:19:51.681164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd803e9573e1'
down_revision: Union[str, None] = '1dd14282e079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicules', sa.Column('boite_vitesse', sa.String(length=20), nullable=True))
    op.add_column('vehicules', sa.Column('nb_portes', sa.Integer(), nullable=True))
    op.add_column('vehicules', sa.Column('nb_places', sa.Integer(), nullable=True))
    op.add_column('vehicules', sa.Column('kilometrage', sa.Integer(), nullable=True))
    op.add_column('vehicules', sa.Column('annee_circulation', sa.Integer(), nullable=True))
    op.add_column('vehicules', sa.Column('crit_air', sa.String(length=10), nullable=True))
    op.add_column('vehicules', sa.Column('permis_requis', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicules', 'permis_requis')
    op.drop_column('vehicules', 'crit_air')
    op.drop_column('vehicules', 'annee_circulation')
    op.drop_column('vehicules', 'kilometrage')
    op.drop_column('vehicules', 'nb_places')
    op.drop_column('vehicules', 'nb_portes')
    op.drop_column('vehicules', 'boite_vitesse')
    # ### end Alembic commands ###
